#!/bin/sh
screen -S minero1 -dm bash -c 'cd ..;python3 minero.py -d 5 -m 1-10 -i 30 -log -parar'
screen -S minero2 -dm bash -c 'cd ..;python3 minero.py -d 5 -m 2-10 -i 30 -parar' 
screen -S minero3 -dm bash -c 'cd ..;python3 minero.py -d 5 -m 3-10 -i 30 -parar'
screen -S minero4 -dm bash -c 'cd ..;python3 minero.py -d 5 -m 4-10 -i 30 -parar'  
screen -S minero5 -dm bash -c 'cd ..;python3 minero.py -d 5 -m 5-10 -i 30 -parar' 
screen -S minero6 -dm bash -c 'cd ..;python3 minero.py -d 5 -m 6-10 -i 30 -parar'
screen -S minero7 -dm bash -c 'cd ..;python3 minero.py -d 5 -m 7-10 -i 30 -parar'  
screen -S minero8 -dm bash -c 'cd ..;python3 minero.py -d 5 -m 8-10 -i 30 -parar'  
screen -S minero9 -dm bash -c 'cd ..;python3 minero.py -d 5 -m 9-10 -i 30 -parar'  
screen -S minero10 -dm bash -c 'cd ..;python3 minero.py -d 5 -m 10-10 -i 30 -parar'  
